// const dummyData = [
//   {
//     user: "67555adb6635b9a4fa1b2c7c",
//     propertyType: "For Rent",
//     category: "PG",
//     role: "Rental Provider",
//     location: {
//       city: "New Delhi",
//       state: "New Delhi",
//       locality: "New Delhi",
//       subLocality: " Uttam Nagar",
//     },
//     propertyStatus: "Active",
//     images: [
//       {
//         name: "pg_room.jpg",
//         url: "https://housing-images.n7net.in/01c16c28/ffe41bd77f6e8892f9146a54106ff434/v0/p/3_rk-for-rent-uttam_nagar_new_delhi-New+Delhi-bedroom.jpg,  , ",
//       },
//       {
//         name: "common_area.jpg",
//         url: "https://housing-images.n7net.in/01c16c28/ffe41bd77f6e8892f9146a54106ff434/v0/large/3_rk_-for-rent-uttam_nagar_new_delhi-New+Delhi-bedroom.jpg,",
//       },
//       {
//         name: "common_area.jpg",
//         url: "https://housing-images.n7net.in/01c16c28/6fb520822af4a1451a935ade1e951d6a/v0/medium/3_rk_-for-rent-uttam_nagar_new_delhi-New+Delhi-bedroom.jpg",
//       },
//       {
//         name: "common_area.jpg",
//         url: "https://housing-images.n7net.in/01c16c28/c64cf74df2aeeb54ce6ddf24a8961b05/v0/medium/3_rk_-for-rent-uttam_nagar_new_delhi-New+Delhi-bedroom.jpg",
//       },
//     ],
//     video:
//       "https://www.instagram.com/stories/surjeet_solanki07/3584477151264817914?utm_source=ig_story_item_share&igsh=dWFtcHdpYnc1Z21s",
//     reviews: [],
//     subCategory: ["Boys PG", "Girls PG"],
//     roomDetails: {
//       sharingType: ["Double Sharing"],
//       bedCount: 2,
//       attachedBathroom: true,
//       balcony: false,
//       roomSize: "150 sqft",
//     },
//     mealDetails: {
//       mealIncluded: true,
//       mealType: ["Both"],
//       mealFrequency: ["Breakfast", "Dinner"],
//       customizationAllowed: true,
//     },
//     availabilityStatus: "Available",
//     availableFrom: "2025-03-15",
//     ageOfProperty: 3,
//     description:
//       "Well-maintained PG for boys with all modern facilities and meals included.",
//     amenities: {
//       wifi: true,
//       housekeeping: true,
//       laundry: false,
//       powerBackup: true,
//       security24x7: true,
//       commonRefrigerator: false,
//       ROWater: false,
//       cookingAllowed: true,
//       twoWheelerParking: true,
//       fourWheelerParking: false,
//       airConditioning: true,
//       geyser: true,
//       lift: true,
//       gym: false,
//       swimmingPool: false,
//       studyTable: true,
//       wardrobe: false,
//       TV: true,
//       microwave: false,
//       recreationRoom: true,
//       hotWater: true,
//       readingRoom: false,
//       garden: false,
//     },
//     rules: {
//       timings: {
//         entry: "08:00 AM",
//         exit: "10:00 PM",
//       },
//       guestPolicy: "Guests allowed after 8 PM",
//       smokingAllowed: false,
//       alcoholAllowed: false,
//       petsAllowed: false,
//     },
//     otherFeatures: {
//       separateEntryForRooms: true,
//       noOpenDrainageAround: true,
//       petFriendly: false,
//       wheelChairFriendly: true,
//       rainWaterHarvesting: true,
//       cornerProperty: false,
//     },
//     societyBuildingFeatures: {
//       swimmingPool: false,
//       security24x7: true,
//       gymFitnessCentre: true,
//       shoppingCenter: false,
//       clubHouse: false,
//       childrenPlayArea: true,
//       sportsFacilities: false,
//       joggingWalkingTracks: false,
//       gardenParks: true,
//       communityHalls: false,
//       cinemaRoom: false,
//       libraryReadingRoom: true,
//     },
//     nearbyPlaces: {
//       hospital: true,
//       school: true,
//       metro: true,
//       mall: true,
//       market: true,
//       railway: false,
//       airport: true,
//       highway: true,
//       busStation: false,
//     },
//     pricing: {
//       monthlyRent: 10000,
//       securityDeposit: 20000,
//       electricityCharges: "As per usage",
//       otherCharges: "500 for maintenance",
//     },
//     createdAt: "2025-02-08T11:17:42.853Z",
//     updatedAt: "2025-02-08T11:17:42.853Z",
//   },

//   // Event Space Property
//   {
//     user: "67555adb6635b9a4fa1b2c7c",

//     propertyType: "For Rent",
//     category: "EventSpace",
//     role: "Rental Provider",
//     location: {
//       city: "Kolkata",
//       state: "West Bengal",
//       locality: "Salt Lake",
//       subLocality: "Sector V",
//       apartment: "Event Plaza",
//       houseNumber: "77B",
//     },
//     propertyStatus: "Active",
//     images: [
//       {
//         name: "event_space_1.jpg",
//         url: "https://images.unsplash.com/photo-1515165562835-c70d55fd65e7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//       {
//         name: "event_space_1.jpg",
//         url: "https://images.unsplash.com/photo-1515165562835-c70d55fd65e7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//       {
//         name: "event_space_1.jpg",
//         url: "https://images.unsplash.com/photo-1515165562835-c70d55fd65e7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//       {
//         name: "event_space_1.jpg",
//         url: "https://images.unsplash.com/photo-1515165562835-c70d55fd65e7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//       {
//         name: "event_space_1.jpg",
//         url: "https://images.unsplash.com/photo-1515165562835-c70d55fd65e7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//       {
//         name: "event_space_2.jpg",
//         url: "https://images.unsplash.com/photo-1553531384-397f9a2b47b1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
//       },
//     ],
//     video: "https://www.youtube.com/watch?v=ScMzIvxBSi4",
//     reviews: [
//       {
//         _id: "60d0fe4f5311236168a10abe",
//         user: "60d0fe4f5311236168a10df0",
//         property: "60d0fe4f5311236168a109b3",
//         stars: 5,
//         text: "The event space was perfect for our conference.",
//       },
//       {
//         _id: "60d0fe4f5311236168a10abf",
//         user: "60d0fe4f5311236168a10df1",
//         property: "60d0fe4f5311236168a109b3",
//         stars: 4,
//         text: "Spacious and well-equipped venue.",
//       },
//     ],

//     // EventSpace-specific fields
//     subCategory: "Event Space",
//     type: "Event Space",
//     propertyDetails: {
//       totalGuests: 300,
//       seatingArrangement: {
//         theaterStyle: 250,
//         classroomStyle: 150,
//         banquetStyle: 200,
//         conferenceStyle: 100,
//       },
//     },
//     pricing: {
//       price: { amount: 500000, currency: "INR" },
//       maintenanceCharges: {
//         amount: 10000,
//         currency: "INR",
//         frequency: "Monthly",
//       },
//       rentalDetails: {
//         monthlyRent: 75000,
//         securityDeposit: 150000,
//         hourlyRent: 2000,
//       },
//     },
//     nearbyPlaces: {
//       hospital: true,
//       school: true,
//       metro: true,
//       mall: true,
//       market: true,
//       railway: false,
//       airport: true,
//       highway: false,
//       busStation: true,
//     },
//     amenities: {
//       projector: true,
//       screen: true,
//       soundSystem: true,
//       lightingSetup: true,
//       airConditioning: true,
//       WiFi: true,
//       cateringServices: true,
//       decorationServices: false,
//       stageSetup: true,
//       podium: true,
//       parkingFacilities: { covered: true, open: false },
//       securityServices: true,
//       cleaningServices: true,
//     },
//     facilities: {
//       restrooms: true,
//       changingRoom: true,
//       powerBackup: true,
//       photoBooth: false,
//     },
//     availableSpaces: {
//       indoorSpace: true,
//       outdoorSpace: false,
//       balconyAccess: false,
//     },
//     bookingDetails: {
//       minimumBookingDuration: "4 hours",
//       maximumBookingDuration: "12 hours",
//       cancellationPolicy: "50% refund if cancelled 24 hours prior",
//     },
//     additionalServices: {
//       eventPlannerSupport: true,
//       technicalStaffOnSite: true,
//       customizableLayouts: true,
//       loungeArea: true,
//     },
//     rules: {
//       alcoholAllowed: false,
//       smokingAllowed: false,
//       petFriendly: false,
//       noiseLimit: "70 dB",
//       decorRestrictions: "No confetti allowed",
//     },
//     availabilityStatus: "Ready to Move",
//     ageOfProperty: 3,
//     description:
//       "Spacious event space ideal for corporate events, conferences, and workshops with modern amenities.",
//     createdAt: "2025-02-08T11:17:42.853Z",
//     updatedAt: "2025-02-08T11:17:42.853Z",
//   },
// ];

// module.exports = dummyData;
